"""add idempotency key to transactions

Revision ID: 943151c8f5a0
Revises: c4ab8f0390b6
Create Date: 2026-08-22 22:25:07.742886

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "943151c8f5a0"
down_revision: str | Sequence[str] | None = "c4ab8f0390b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions", sa.Column("idempotency_key", sa.String(length=100), nullable=True)
    )
    op.create_unique_constraint(
        "uq_transactions_user_id_idempotency_key", "transactions", ["user_id", "idempotency_key"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_transactions_user_id_idempotency_key", "transactions", type_="unique")
    op.drop_column("transactions", "idempotency_key")
    # ### end Alembic commands ###
